site_name: Syps Documentatie
site_url: https://readthedocs.org/projects/Syps-Documentatie

nav:
  - Home: index.md
  - Installatie: INSTALLATION.md
  - Configuratie: CONFIGURATIE.md
  - Handleiding beheer: manual/MANUAL.md
  - Gespreksresultaten: manual/GESPREKSRESULTATEN.md
  - Nieuws en werkinstructies: manual/NIEUWS-WERKINSTRUCTIES.md
  - Skills: manual/SKILLS.md
  - Links: manual/LINKS.md
  - Definition of Done: DEFINITIONOFDONE.md
  - Security: SECURITY.md
  
theme: readthedocs
