site_name: Syps Documentatie
site_url: https://readthedocs.org/projects/Syps-Documentatie

nav:
  - Home: index.md
  - Installatie: INSTALLATION.md
  - Configuratie: CONFIGURATIE.md
  - Handleiding beheer: MANUAL.md
  - Definition of Done: DEFINITIONOFDONE.md
  - Security: SECURITY.md
  
theme: readthedocs
