apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "kiss-eck.name" . }}
  labels:
  {{- include "kiss-eck.labels" . | nindent 4 }}
spec:
  nodeSets:
  - config:
      node.roles:
      - data
      - ingest
      - master
      node.store.allow_mmap: false
    count: 3
    name: default
  version: {{ .Values.elasticVersion }}